### ISSUE TITLE
Adding support for the autocomplete API

### ISSUE THREAD

**Issue by karllhughes** [Wisembly/clearbit-php#1]
I was about to start a small project using the Clearbit [Autocomplete API](https://clearbit.com/docs#autocomplete-api) when I found this. Are you interested in supporting it as well? I'm happy to do the work in my own fork and make a PR if you're open to it.

Thanks!

**Comment by krichprollsch** [comment]
Hello Karl,

Thank you very much for your contribution, that's very nice! I will take time today to test it, but it looks good!
