### ISSUE TITLE
Upgrading Guzzle

### ISSUE THREAD

**Issue by karllhughes** [Wisembly/clearbit-php#3]
Just wondering if there's a reason this project uses Guzzle 3? Any plans to upgrade to 5 or 6 in the near future? Any interest?

Would be happy to help with the upgrade process if that's interesting to you at all.

**Comment by krichprollsch** [comment]
Upgrading guzzle would be great indeed. But last time I take a look at Guzzle, the support of service description was missing... I didn't check that's point anymore.

But I heard of [Httpplug](http://docs.httplug.io/en/latest/) which looks very nice and allow us to abstract the http layer.
I prefer this idea instead of upgrade Guzzle. WDYT ?

**Comment by karllhughes** [comment]
I see. I have used Guzzle quite a bit, but this is my first time with the
Service classes. I see they have a new repo for services, and it looks like
someone's working on making it compatible with Guzzle 6:
https://github.com/guzzle/guzzle-services/issues/89

I'll just keep an eye on that issue and maybe do some reading in the
meantime. Thanks!

**Comment by karllhughes** [comment]
As for Httpplug, I have not used it or looked into it much, but :+1: for anything that uses the PSR-7 standard. That's initially why I was interested in a switch to Guzzle 6, but it could be interesting to try something completely new.

Either way might take some heavy refactoring, but I'm up for helping.

**Comment by Taluu** [comment]
@krichprollsch already lnows my point of view : guzle 3 should just burn. But we are indeed looking at HttpPlug or even trying to migrate to at least Guzzle 4 (for legacy reason on our main application, which has this lib as a dependency).

![image](https://cloud.githubusercontent.com/assets/239685/11815965/88fbceec-a34e-11e5-9e1b-dbe56e83bbe0.png)

**Comment by karllhughes** [comment]
Haha, fortunately for my app, Guzzle 3 and Guzzle 6 are in completely
different namespaces so I can use both at the moment.

**Comment by Taluu** [comment]
That's also why we are also currently using guzzle 3 and guzzle 4 :{

**Comment by krichprollsch** [comment]
Hey here, I'm currently working on a [2.0](https://github.com/Wisembly/clearbit-php/tree/2.0).
The idea is to use httplug to abstract http client usage.
I try the lib [jane-openapi](https://github.com/jolicode/jane-openapi) to keep the generation from a json file.

I like the result.

Currently I have implemented only the combined enrichment API.

**Comment by krichprollsch** [comment]
since the `2.0` is released, this is not relevant anymore.
